name: downloadArtifact 

on:
  workflow_run:
    workflows: [uploadArtifact]
    types: [completed]
jobs:
  downloadArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - name: Download a single artifact from another workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          name: artifacts
          path: extracted
          workflow: upload-artifact-wf.yaml 
          if_no_artifact_found: fail
      - name: Extract files
        run: ls -R extracted
        shell: bash
      - name: Archive files
        uses: actions/upload-artifact@v3
        with:
          name: artifactsV2
          path: extracted/*
          retention-days: 1
#  uploadArtifacts:
#    needs: [downloadArtifact]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Archive
#        uses: actions/upload-artifact@v3
#        with:
#          name: artifactsV2
#          path: extracted/*
#          retention-days: 1
#
