name: downloadArtifact 

on:
  workflow_run:
    workflows: [uploadArtifact]
    types: [completed]
jobs:
  downloadArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - name: Download a single artifact from another workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          name: artifacts
          search_artifacts: true
          #run_number: 16
          #run_id: 3310776491 
          path: extracted
          workflow: download-artifact-wf.yaml 
      - name: Extract files
        run: ls -R extracted
        shell: bash
