on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: Za-Re/hello-world-composite-action@v2
        with:
          who-to-greet: 'Zara'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
  prints_finish:
    runs-on: ubuntu-latest
    name: A job to say finish
    steps:
      - name: Echo finish
        run: echo 'finish'
